pipeline {
    agent any
    
    environment {
        IMAGE_NAME = "ganesh2306/python-devops:latest"
    }
    stages {

        stage('Clone Repo') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Ganesh2306/Python-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t python-devops ./app/python-app'
            }
        }
        
        stage('Push Docker Image') {
            steps {
                sh '''
                docker tag python-devops ganesh2306/python-devops:latest
                docker login -u ganesh2306 -p YOUR_DOCKER_PASSWORD
                docker push ganesh2306/python-devops:latest
                '''
            }
        }
   
        stage('Terraform Init') {
            steps {
                sh 'cd terraform && terraform init'
            }
        }

        stage('Terraform Apply') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    sh '''
                    cd terraform
                    terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Update Inventory') {
            steps {
                sh '''
                cd terraform
                IP=$(terraform output -raw instance_public_ip)

                echo "[web]" > ../ansible/inventory.ini
                echo "$IP ansible_user=ubuntu ansible_ssh_private_key_file=/var/lib/jenkins/devops-key.pem" >> ../ansible/inventory.ini
                '''
            }
        }

        stage('Deploy using Ansible') {
            steps {
                sh '''
                export ANSIBLE_HOST_KEY_CHECKING=False
                ansible-playbook -i ansible/inventory.ini ansible/setup.yml
                '''
            }
        }
    }
}
